"""initial

Revision ID: f4770111e3d2
Revises: 
Create Date: 2026-05-04 12:05:06.070104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4770111e3d2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_programs_user_id', 'user_programs', ['user_id'], unique=False)
    op.create_index('ix_user_weight_logs_user_exercise', 'user_weight_logs', ['user_id', 'exercise_id'], unique=False)
    op.create_index('ix_workout_sessions_user_completed', 'workout_sessions', ['user_id', 'completed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_workout_sessions_user_completed', table_name='workout_sessions')
    op.drop_index('ix_user_weight_logs_user_exercise', table_name='user_weight_logs')
    op.drop_index('ix_user_programs_user_id', table_name='user_programs')
    # ### end Alembic commands ###
